version: '2.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health"]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - 9200:9200
    networks:
      - elk
  
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.9
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "12201:12201/udp"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk
  
  golang:
    image: golang:1.19-alpine
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    volumes:
      - ../../:/go/src/github.com/sofianhw/go-elk-workshop
      - ../../logs/:/logs/
    working_dir: /go/src/github.com/sofianhw/go-elk-workshop
    command: go run main.go
    ports: 
      - 8080:8080
    networks:
      - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.9
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ../../logs/:/logs/
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/api/status"]
      interval: 3s
      timeout: 3s
      retries: 50
    ports:
      - 5601:5601
    networks:
      - elk
  
  plop:
    image: alpine
    volumes:
      - ./:/home/
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: "staging"
    links:
      - logstash:logstash
    depends_on:
      - logstash
    command: /bin/sh /home/test.sh
    networks:
      - elk

networks:
  elk:
    driver: bridge